name: Build

on:
  push:
    branches: [master]

jobs:
  source:
    name: Source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install required libraries
        run: sudo apt update && sudo apt install -y libopus-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          profile: minimal
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
