name: Build

on:
  push:
    branches: [master]

jobs:
  source:
    name: Source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install required libraries
        run: sudo apt update && sudo apt install -y libopus-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          profile: minimal
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

          
  docker-images:
    name: Docker Dev Images (shard & queue)
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -  name: Build and push shard image
         uses: docker/build-push-action@v4
         with:
            push: true
            file: dev/Dockerfile
            context: .
            tags: memothelemo/kyoka:dev
            # https://docs.docker.com/build/ci/github-actions/cache/#registry-cache
            cache-from: type=gha
            cache-to: type=gha,mode=max

    # TODO: Find a way to speed Docker builds by caching from the last step.
    #   -  name: Build and push gateway queue image
    #      uses: docker/build-push-action@v4
    #      with:
    #         push: true
    #         file: dev/Dockerfile
    #         context: .
    #         tags: memothelemo/kyoka:dev
